FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN python -m venv .venv && \
    . .venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

CMD ["/bin/bash", "-c", "source .venv/bin/activate"]